### ISSUE TITLE
Does not show "Submit ticket"  on woocommerce order

### ISSUE THREAD

**Issue by alexlii1971** [nanodesigns/nanosupport#102]
**Describe the bug**
Does not show "Submit ticket"  on woocommerce order

**To Reproduce**
We are using oceanwp theme https://wordpress.org/themes/oceanwp/

It has more than 600,000+ download, I am not sure whether the issue is theme related.

**Expected behavior**
A "submit ticket" button show up in woo order rows.

**Screenshots**
http://prntscr.com/uugzo9

http://prntscr.com/uuh2r7

**System Status (you can copy paste the system status report from the plugin):**

WordPress version: 5.5.1;
NanoSupport version: 0.6.0;
E-Commerce?: Enabled;
Active Theme: OceanWP - 1.8.9; ;
Debug mode: Off;
Multisite?: Yes;
Site Language: en_US;
Server: nginx/1.16.1;
PHP Memory Limit: 256 MB;
PHP version: 7.4.7;
MySQL version: 5.5.5.

...

Active Plugins (33):
Admin CSS MU (2.5) - by Arun Basil Lal; Autoptimize (2.7.7) - by Frank Goossens (futtta); Booster Plus for WooCommerce (5.3.2) - by Pluggabl LLC; Code Snippets (2.14.0) - by Code Snippets Pro; Customizer Export/Import (0.9.2) - by The Beaver Builder Team; Dynamic Widgets (1.5.16) - by Qurl; EWWW Image Optimizer (5.7.1) - by Exactly WWW; Forminator (1.14.0) - by WPMU DEV; Insert Headers and Footers (1.4.6) - by WPBeginner; jQuery Manager for WordPress (1.10.6) - by Remzi Cavdar; NanoSupport (0.6.0) - by nanodesigns; Product Tabs Manager for WooCommerce (1.1.3.3) - by BeRocket; Rank Math SEO (1.0.48.2) - by Rank Math; Table of Contents Plus (2002) - by Michael Tran; Tawk.to Live Chat (0.4.3) - by Tawkto; Themify - WooCommerce Product Filter (1.3.1) - by Themify; Woocommerce Shipping Packages (1.1.7) - by OneTeamSoftware; WooPricely - Dynamic Pricing & Discounts (1.3.3) - by zendcrew; WP DB Search & Replace (0.2.0) - by Weptile; Variation Swatches for WooCommerce - Pro (1.0.52) - by Emran Ahmed; Variation Swatches for WooCommerce (1.0.86) - by Emran Ahmed; WooCommerce Accepted Payment Methods (0.7.0) - by jameskoster; WooCommerce PayPal Checkout Gateway (2.0.3) - by WooCommerce; WooCommerce Orders Tracking Premium (1.0.4) - by VillaTheme; WooCommerce Photo Reviews Premium (1.1.4.5) - by VillaTheme; WooCommerce (4.5.1) - by Automattic; WPB Show Product Sales Number for WooCommerce (1.0.2) - by wpbean; WP Legal Pages Pro (7.6) - by WPEkaClub; WP Legal Pages (2.4.5) - by WPEka Club; YITH Google Product Feed for WooCommerce Premium (1.1.13) - by YITH; YITH WooCommerce Bulk Product Editing Premium (1.2.24) - by YITH; YITH WooCommerce Checkout Manager (1.4.0) - by YITH; YITH WooCommerce SMS Notifications Premium (1.4.7) - by YITH.

**Comment by mayeenulislam** [comment]
> _Does not show "Submit ticket" on woocommerce order_

I'm afraid I couldn't get you correctly. There was **no "Submit Ticket" button was ever introduced in WC Order**.
Why are you expecting a "Submit Ticket" button in WC Order?

**Comment by alexlii1971** [comment]
Hello,

Please check this url as sample:

https://www.beautifulhalo.com/info/how-can-i-return-an-item.html

We are using google merchant center and google ads to promote sales, and google require clearly show the return and refund policy and the process.

So, this is important feature for Woocommerce site.
Thanks

**Comment by mayeenulislam** [comment]
I'm afraid, this is a WooCommerce feature. They modified the WC order page and added a link toward the Submit ticket page.
