### ISSUE TITLE
Ticket ID or Follow-up Number 

### ISSUE THREAD

**Issue by mmoralesf** [nanodesigns/nanosupport#106]
**Is your feature request related to a problem? Please describe.**
We need a number to which we can relate a case. There is no apparent way to enable this at this moment, I conclude. I want to make a reference to a case and I can’t without sharing a screenshot or so. 

**Describe the solution you'd like**
To every entry assign an ID such as a page ID or post ID. I assume this could be an ID for a given custom type content.

**Comment by mayeenulislam** [comment]
Thank you for the request. The feature is in pipeline and will be available on `v0.6.1`, insha'Allah.

For details, please see #78
