### ISSUE TITLE
button text color needs to be changed

### ISSUE THREAD

**Issue by nezam05** [nanodesigns/nanosupport#13]
![screenshot from 2016-10-05 16 00 20](https://cloud.githubusercontent.com/assets/14247241/19108993/14d5cab8-8b15-11e6-84b3-286ee5b68de4.png)

Please check the screenshot attached. The button text "Submit Ticket" is visible when the visitor hover the mouse on it. I have checked with chrome and firefox browser and changed theme multiple times to confirm that its an issue with plugin css.

**Comment by mayeenulislam** [comment]
@nezam05 Thanks for testing things in Bengali.

I'm afraid, I cannot replicate the thing. :(
What theme is that? Can we have a live URL?

**Comment by nezam05** [comment]
Welcome.
I am using Divi theme. and just found out that changing theme's color scheme from red to some other color solves this. I guess, previous theme was also using a red color scheme. 
You can close the topic.
