### ISSUE TITLE
How to show department options in submit ticket form?

### ISSUE THREAD

**Issue by naftalent** [nanodesigns/nanosupport#17]
Dear NanoSupport,

How to show department options in submit ticket form? In options page I didn't found anything for this option.

Best regards.

**Comment by mayeenulislam** [comment]
@naftalent Duplicate issue. Please follow:
https://github.com/nanodesigns/nanosupport/issues/2

I'm closing this one. Issue#2 is set milestone for `v0.3.0`. Please wish us good luck.
