### ISSUE TITLE
How to search Knowledgebase separately?

### ISSUE THREAD

**Issue by mayeenulislam** [nanodesigns/nanosupport#18]
Chris from ibousa.org asked:

> Is there a way to search all items in the Knowledgebase?

**Comment by mayeenulislam** [comment]
Currently with NanoSupport `v0.2.2` the knowledgebase **cannot** be searched separately from site search.
But the **site search works well** with NanoSupport knowledgebase.

A system in under development to let the user search Knowledgebase search separately. InshALLAH we will unveil very soon.

**Comment by fang-yu** [comment]
I use DIVItheme, but seem like the wordpress search bar can not even search the knowledge base post.

**Comment by mayeenulislam** [comment]
@fang-yu We second to the issue. Because from NanoSupport core the [Knowledgebase entries are searchable](https://github.com/nanodesigns/nanosupport/blob/v0.4.1/includes/ns-cpt-knowledgebase.php#L56-L57).

It might be _your theme_ that is prohibiting exhibiting any other Custom Post Type to appear on the search result. In that case what we can suggest is to tweak the search result with the `pre_get_posts` hook:

```php
<?php
function tweaking_mytheme_search_result( $query ) {
    if( is_admin() ) return;

    if( is_search() && $query->is_main_query() ) {
        $query->set('post_type', 'nanodoc');
    } 
}

add_action( 'pre_get_posts', 'tweaking_mytheme_search_result' );
```

Source: [WordPress StackExchange](https://wordpress.stackexchange.com/a/249004/22728) by _tormorten_

**Comment by fang-yu** [comment]
Thanks. But do you mean that I could add the follwing code to the functions.php in my theme folder?
```
<?php
function tweaking_mytheme_search_result( $query ) {
    if( is_admin() ) return;

    if( is_search() && $query->is_main_query() ) {
        $query->set('post_type', 'nanodoc');
    } 
}

add_action( 'pre_get_posts', 'tweaking_mytheme_search_result' );
```

**Comment by mayeenulislam** [comment]
Yes, not in the parent theme, but in your child theme's `functions.php` so that theme update won't wash the code away.

**Comment by mayeenulislam** [comment]
We are glad to announce the first Premium Add-on for NanoSupport:

> [**Addon: Knowledgebase Search** - NanoSupport](https://creativemarket.com/nanodesigns/3461090-NanoSupport-Knowledgebase-Search?ref=nsgithub)

Requires NanoSupport `v0.6.0`

It will suggest from the Knowledgebase Docs while submitting a new ticket, and it will enable a separate search feature in Knowledgebase. 😃
