### ISSUE TITLE
Let the user select the Support Department

### ISSUE THREAD

**Issue by mayeenulislam** [nanodesigns/nanosupport#2]
As **Jonathan Bosssenger** [suggested](https://wordpress.org/support/topic/great-support-ticketing-system):

> It would also be useful if the user submitting the ticket could select from a list of departments when they submit their ticket

**Comment by mayeenulislam** [comment]
The feature was **initially skipped** because our philosophy was:

> The **user should not** assign a ticket to a department, it's the admin/manager who has the authority to assign a ticket to respective department.

_Isn't it?_
How is your thought powerful to add this as a feature?

**Comment by jonathanbossenger** [comment]
Hmmm good point. I see what you mean.

However I would counter by saying this. If you allow the customer to select the department they think the request belongs to it is possible that they select the correct department, thereby allowing the admin/manager a quicker process to approve the ticket. If it is already in the correct department, it saves him from having to select the department.

If you are the manager and you have to approve 100 tickets, not having to select the department would  save time.

**Comment by mayeenulislam** [comment]
Yap, may be good, but there are **bulk edit** feature available in admin panel to deal with it.

Anyway, I think we should provide a way of activating/deactivating this. So that it'd be more flexible and admin'll decide whether they want to provide the feature to the _Support Seeker_ or not.

**Comment by wildbuttrueblue** [comment]
Have to concur with Jonathon, a feature permitting the customer to select the department would be beneficial, at least to some, such as myself.  One the reduction in time required for the manager to assign the tickets, as well as by permitting the customer to select the 'correct' department, the response time to the ticket could potentially be reduced, in some instances significantly.  While I like the plugin, this ability missing from the plugin is the one thing that essentially causes it not to work in my environment.  

~Respect
Kevin

**Comment by mayeenulislam** [comment]
Respect to your opinion and vote for the feature, @wildbuttrueblue 
We duly noted this.
