### ISSUE TITLE
Permalink Structure Changes for Knowledgebase

### ISSUE THREAD

**Issue by avatarati** [nanodesigns/nanosupport#20]
Hello,

In the knowledgebase, the categories should be used in the permalink structure. It seems to skip past the category altogether when creating URL structures.

Example:

Let's say I have a category of "Configuration" and a topic within that category called "Setting Up Your Client."

This should produce a URL structure such as: http://www.example.com/knowledgebase/configuration/setting-up-your-client

As it stands, it is treating "knowledgebase" as the only category, so URL's are built like this:

http://www.example.com/knowledgebase/setting-up-your-client

As a note, my permalink structure is set to: www.example.com/%category%/%post-name%/

**Comment by mayeenulislam** [comment]
Very impressive point. 👍  
We should work on this ASAP.
Thank you for notifying us.

**Comment by avatarati** [comment]
Mayeenulislam, 

Thank you for your quick response.

I just wanted to say that I love your plugin. It is simple, clean, and well-designed. Even the code looks great and is organized/presented well. 

I look forward to future improvements and modifications.

Thank you for dedicated effort in developing this.

**Comment by mayeenulislam** [comment]
So nice of you.
We would love if [**you review our plugin**](https://wordpress.org/support/plugin/nanosupport/reviews/#new-post) at WordPress.org.

**Comment by mayeenulislam** [comment]
The current development workflow is to add Knowledgebase Categories before the KB Doc slug. So that we can have recursive slugs, if nested categories are found. It will [inshALLAH] support `n` numbers of nesting (6 tested):

```
http://example.com/knowledgebase/category-1/kb-doc
http://example.com/knowledgebase/category-1/category-2/kb-doc
http://example.com/knowledgebase/category-1/category-2/.../category-n/kb-doc
```

May I request your opinion, on:
**Is there any type of possibilities, user might want from such URL rewriting?**
