### ISSUE TITLE
Users can set them as support agent themselves

### ISSUE THREAD

**Issue by wptech68** [nanodesigns/nanosupport#23]
### Actual behavior

User can set himself as support agent

### Steps to reproduce

1. Login as a user
2. Go to profile
3. Set himself as support agent

### Expected behavior

Setting a support agent should only be available for admins and/or other agents, and not for everyone.
even is not a big problem since they cannot be assigned to a ticket, they should not see this option on their profiles

**Comment by wptech68** [comment]
I dont see this as an enhancement, but a bug to be fixed
however, I dont see how to label tickets here

**Comment by mayeenulislam** [comment]
We think making or unmaking support agent should be reserved only for the admins (`administrator` and `editor`), and **not** for the agents.

**Comment by mauwiks** [comment]
I [disabled the admin panel](https://www.wpbeginner.com/wp-tutorials/how-to-disable-wordpress-admin-bar-for-all-users-except-administrators/) for other users as administrator to avoid this issue.
