### ISSUE TITLE
Error in submitting tickets

### ISSUE THREAD

**Issue by bondzie** [nanodesigns/nanosupport#25]
### Actual behavior

Hi,

my website is: www.trademenperhour.com

Nano Support is a great plugin. However, I am not able to get it working in my installation. Please visit – http://www.trademenperhour.com/submit-ticket/

I have activated the plugin but it is not allowing users to enter details in the details box (a required field) and therefore tickets are unable to be submitted. 

Please advise a fix.

Regards,

Eric

### Steps to reproduce

1. 
2. 
3. 

### Expected behavior

Submission of a ticket
 
### System Status

NanoSupport Environment
WordPress version	4.7
NanoSupport version	0.3.0
Active Theme	Taskerdev – 1.9.8.2
Debug mode	Off
Multisite?	No
Site Language	en_GB
Server	Apache
PHP Memory Limit	256 MB
PHP version	5.6.27
MySQL version	5.6.32

Active Plugins (38)
![screen shot 2017-01-09 at 17 09 32](https://cloud.githubusercontent.com/assets/25012358/21775552/82df9ed4-d68e-11e6-8283-58b175418917.png)

TaskerDev Gateways (1.0)	by SiteMile.com
Admin Menu Editor (1.7.3)	by Janis Elsts
WP Affiliate Manager (2.3.6)	by wp.insider, wpaffiliatemgr
Akismet (3.2)	by Automattic
Amazon Associates Link Builder (1.3.2)	by Amazon Associates Program
Amazon Master (5.0.4)	by TechGasp
bbPress (2.5.12)	by The bbPress Community
Breadcrumb NavXT (5.6.0)	by John Havlik
BuddyPress (2.7.4)	by The BuddyPress Community
Google Maps CP (1.0.1)	by CodePeople
Contact Form DB (2.10.28)	by Michael Simpson
Contact Widgets (1.3.4)	by GoDaddy
Dashboard Widgets Suite (1.3)	by Jeff Starr
Easy Digital Downloads (2.6.17)	by Easy Digital Downloads
EDD and WP Affiliate Integration (1.1)	by Tips and Tricks HQ
Google Analytics Dashboard for WP (4.9.5)	by Alin Marcu
iframe (4.3)	by webvitaly
Jetpack by WordPress.com (4.4.2)	by Automattic
MailChimp for WordPress (4.0.11)	by ibericode
MOJO Marketplace (1.1.0)	by Mike Hansen
NanoSupport (0.3.0)	by nanodesigns
Pricing Table by Supsystic (1.3.7)	by supsystic.com
Simple Job Board (2.4.2)	by PressTigers
Page Builder by SiteOrigin (2.4.21)	by SiteOrigin
SiteOrigin Widgets Bundle (1.7.2)	by SiteOrigin
Spider FAQ (1.2)	by http://web-dorado.com/
Theme My Login (6.4.7)	by Jeff Farthing
ThirstyAffiliates (2.6.4)	by ThirstyAffiliates
Travelpayouts (0.6.3)	by travelpayouts
UpdraftPlus - Backup/Restore (1.12.30)	by UpdraftPlus.Com, DavidAnderson
Widget Options (3.1)	by Phpbits Creative Studio
Yoast SEO (4.0.2)	by Team Yoast
WordPress Social Login (2.3.0)	by Miled
WP-PageNavi (2.91)	by Lester 'GaMerZ' Chan
WP Sitemap Page (1.6)	by Tony Archambeau
WP Statistics (11.0.2)	by Greg Ross & Mostafa Soufi
Categories to Tags Converter Importer (0.5)	by wordpressdotorg
Forum - wpForo (1.1.1)	by gVectors Team (A. Chakhoyan, R. Hovhannisyan)
> NanoSupport: vX.X.X

> WordPress: vX.X.X

> Active Theme: 

> Active Plugins:

**Comment by mayeenulislam** [comment]
You have a lot of plugins active. Seems a plugin conflict of some sort.

Let's try a quick fix, by disabling the TinyMCE editor in front end:

```php
function disable_nanosupport_editor( $array ) {
	$array['tinymce'] = false;
	return $array;
}
add_filter( 'ns_wp_editor_specs', 'disable_nanosupport_editor', 11 );
```

Please place the block of code at the end of your theme's `functions.php` inside PHP code block.
It will disable the TinyMCE editor in the Submit Ticket page.
Let me debug things a bit.

**Comment by mayeenulislam** [comment]
## Primary Assumption: Conflict seems the Spider FAQ plugin
![plugin-conflict-with-spider-faq](https://cloud.githubusercontent.com/assets/4551598/21776058/d637944a-d6c2-11e6-860c-3a447b9357b9.png)

**Comment by bondzie** [comment]
Your assumption is correct!  I have deactivated and removed the plugin.

Thanks for a quick response, it's much appreciated!  Keep up the good work!

**Comment by mayeenulislam** [comment]
## Bug Identified in Spider FAQ plugin

With the WP_DEBUG enabled, and the help of Debug Bar the following error came up:

> **Uncaught ReferenceError:** `spider_faq_plugin_url` is not defined
> http://example.com/wp-content/plugins/spider-faq/js/editor_plugin.js?wp-mce-4403-20160901 line 21

And they did a very unwanted code (as of Release 1.2) in `\wp-content\plugins\spider-faq\faq.php` [on line 2047](https://github.com/wp-plugins/spider-faq/blob/c5a66aae55e9fc4aaf1a979e145affb9922ccddd/faq.php#L2047-L2055):

```php
function add_button_style_Spider_Faq() {
  ?>
  <script>
    var spider_faq_plugin_url = '<?php echo plugins_url(plugin_basename(dirname(__FILE__))); ?>'; 
  </script>
  <?php
}

add_action('admin_head', 'add_button_style_Spider_Faq');
```

## Remedy
I'd recommend you to file them a Support Ticket with the findings to fix the code with `wp_localize_script()`. You can refer them here in this ticket too.

---

**PS.** NanoSupport has a built-in Knowledgebase ([How to Use](https://github.com/nanodesigns/nanosupport/wiki/How-to-Use)), though it's not something similar to FAQ, but you can use it for Public documentation. For FAQ thing, you can have a look at Issue #15.
