### ISSUE TITLE
Can we strip out `Priority` from the public portion?

### ISSUE THREAD

**Issue by mayeenulislam** [nanodesigns/nanosupport#26]
User nh123 [requested an enhancement](https://wordpress.org/support/topic/priority-3/):

> _Can we remove the “priority field for users. We don’t need the field and therefore we don’t see any reason the users should think about and set priorities to their contact._

**Comment by mayeenulislam** [comment]
With version `0.3.0`, I'm afraid, you can't.

But there surely a mechanism should be included so that admin can include/exclude the feature where necessary. We've duly noted this, and will inshALLAH implement on any upcoming release.

**Comment by wptech68** [comment]
I agree to have an admin option to remove the priority options on  ticket submit form
