### ISSUE TITLE
Email link problem

### ISSUE THREAD

**Issue by wptech68** [nanodesigns/nanosupport#31]
looks something is wrong with the link received by email notifications pointing to the ticket
it links to something like http://domain.com/?post_type=nanosupport#038;p=4129 instead of the ticket link

**Comment by mayeenulislam** [comment]
Actually we couldn't recreate the same. :disappointed: 

## Local Server Test
![pending-link-local](https://cloud.githubusercontent.com/assets/4551598/23450224/3f50a5dc-fe84-11e6-9b22-151c617fff00.png)

## Remote Server Test
![pending-link-server](https://cloud.githubusercontent.com/assets/4551598/23450239/4f77b68a-fe84-11e6-9889-e04822b32ea5.png)

The link to the ticket, in email, was used in two cases:

1. Notifying about new ticket submission, and
2. Notifying agent about their assignment in a ticket

With your report, we've checked the code and found that, the 1st one's good using the `get_permalink()` - a WordPress' core function to handle this. And with quick tests, we found no bug there. So the bug report seems too localized and need to be checked in that particular condition only.

But with your bug report we found a minor issue in 2nd one that, the _hacky_ `ns_get_pending_permalink()` is not functioning as expected. So we fixed that particular code in response.

**Comment by wptech68** [comment]
I actually received the "unfriendly" link as an administrator when a new ticket was created.
Which php file is the one managing the emails? I will take a look to mine to see if I find something there

**Comment by mayeenulislam** [comment]
Please have a look [here](https://github.com/nanodesigns/nanosupport/blob/d00571bbe977c01bb5e0b2dd45dbd27714ebb429/includes/ns-email-functions.php#L109) in `includes/ns-email-functions.php`.

It's using the WP Core [`get_permalink()`](https://developer.wordpress.org/reference/functions/get_permalink/).

**Comment by wptech68** [comment]
I guess that the permalink is generated "after" the ticket published, so thats the problem
In my list of tickets I have 10 tickets with their own permalink (pretty links), however a recently submitted ticket that is still pending shows a link to http://domain.com/?post_type=nanosupport&p=4132 and is the only one with this structure, and I think is because it is "pending", and thats why the admin when receives the notification about a new ticket created receives this same type of link

also checked these links as support agent and final user, and all of them receive the correct permalink, is just the admin who gets the large link while the ticket is still pending, so 99% the permalink is generated "after" published, which makes sense

not a big problem since admin can deal with that, what I dont know is why the links ads the #038 as shown in the example link http://domain.com/?post_type=nanosupport#038;p=4129

**Comment by mayeenulislam** [comment]
We've a [_hacky_ pretty permalink structure for pending posts](https://github.com/nanodesigns/nanosupport/blob/d00571bbe977c01bb5e0b2dd45dbd27714ebb429/includes/ns-utility-functions.php#L508-L525), but actually it doesn't work in most of the cases. Yes, the pretty permalink only appear while **published**.

The single case that was assigning `#038` is surely a concern, but with no insight, like you, we're in deep ocean, you know. :neutral_face: 

Let's not pray to happen this again. :smiley: But let's wait for another occurrence, so that we can have some clue to dig with.

**Comment by mayeenulislam** [comment]
Could you please inform us, whether _that_ cause a wrong post link with `#038;`:
```
http://example.com/?post_type=nanosupport#038;p=4129
```
All the references I found saying, `#038;` is healthy and equivalent to `&` or `&amp;`, and they won't break things ever.

**Comment by wptech68** [comment]
http://example.com/?post_type=nanosupport#038;p=4129
opens a page listing all tickets as "recent articles" in a standard wordpress layout
but
http://example.com/?post_type=nanosupport&p=4129
works fine redirecting to the permalink for ticket 4129

probably is my server not recognizing the #038; as a &

**Comment by mayeenulislam** [comment]
You didn't share your server info. You can share all the necessary system status using the Plugin's "System Status" submenu under "NanoSupport".
