### ISSUE TITLE
last reply date & user error

### ISSUE THREAD

**Issue by wptech68** [nanodesigns/nanosupport#32]
hi
after upgrading to 0.3.2 with wp 4.7.2 all my tickets show the last reply as made by admin 4hs ago, but thats not correct
I have tickets with last reply from a week ago, an others replied lastly by an agent, but this is not showing like that in the ticket list

so something went wrong with the 0.3.2 upgrade

**Comment by mayeenulislam** [comment]
Could you please share the link of your `Support Desk`?

**Comment by wptech68** [comment]
check yr gmail

**Comment by mayeenulislam** [comment]
Yes, that was ridiculous. We've noticed that too. Thanks for notifying. It's a serious bug. We're extremely sorry!
Let us dig it please.

**Comment by wptech68** [comment]
if I go back replacing with 0.3.1 , will this fix it by now? or is related to database changes made by the upgrade?

**Comment by mayeenulislam** [comment]
For a quick fix, you are requested to fallback to the previous version: v0.3.1:

- Make sure the "Delete all data" field under NanoSupport Settings is unchecked.
- Deactivate and Delete plugin (v0.3.2)
- [Download version v0.3.1](https://downloads.wordpress.org/plugin/nanosupport.0.3.1.zip)
- Install the version from Plugins > Add New > Upload plugin, and activate

This will fix the same user related issue.
But unfortunately the date issue won't resolved and we made a mess :-1: 
The code block responsible for updating `post_modified` [date] was actually updating the `post_date` and that's wrong.
We cordially apologise for the mess. :(

**Comment by wptech68** [comment]
I will better wait to 0.3.3

**Comment by mayeenulislam** [comment]
We're trying not to solve the bugs in v0.3.1 and first get back to v0.3.1 again to not mess things from now on.
Then we will start again inshALLAH.
It's unfortunate, fixing one, mess manywhere. :(

**Comment by wptech68** [comment]
ok, I just reverted to 0.3.1 and all looks fine as before. 
btw, you should also remove 0.3.2 from repository I think, to avoid others messing the whole thing

**Comment by wptech68** [comment]
are u sure 033 fixed the dates problem
just upgraded to 033 but creation date and last update date are sometimes identical, even having some replies on different  days
probably the 032 mess changed the database for those old tickets
didnt test it with new tickets yet

**Comment by mayeenulislam** [comment]
It's the same code for date things that was in v0.3.2
Yes, we apologise that, _that_ particular code, with **no reason _why_**, _could have_ changed some `post_date` in db level. But we couldn't find the reason why.
We will dig it more thoroughly before trying to resolve #28 and need to resolve it in a more bug-free way.
Let's pray for the good.
We wholeheartedly apologise :pray: if anything went wrong with v0.3.2, because our intention was not to mess things, ever. :(
