### ISSUE TITLE
Support agent loses his status on profile update

### ISSUE THREAD

**Issue by wptech68** [nanodesigns/nanosupport#34]
hi

today I found a bug
if a support agent update his profile from standard wp profile page, his "support agent status" is lost so admin needs to set him again as a support agent from admin menu

looks the profile update form , which does NOT show the support agent satus for regular members and agents (which is fine), is sending a hidden blank value when updating the profile, so removing the support agent status for this user.

**Comment by mayeenulislam** [comment]
Bug confirmed. 😞 
Milestone ahead.
Thanks for your constant support. That's unbelievable. 👍
