### ISSUE TITLE
Shortcodes or Other way to display stats

### ISSUE THREAD

**Issue by lifeofaboat** [nanodesigns/nanosupport#36]
Is there a shortcode or other way to get statistics and display them somewhere on a page?  For example, a way to select the number of active issues?

**Comment by mayeenulislam** [comment]
We are afraid, no.
It's because Support Ticketing using NanoSupport is an internal matter dealt with private ticketing. So public statistics seemed unnecessary to us.

But if you can show us good reason, it can be added to the ToDo list.

**Comment by lifeofaboat** [comment]
Thanks!
