### ISSUE TITLE
Translation for PT_BR did not work

### ISSUE THREAD

**Issue by DataAmerica** [nanodesigns/nanosupport#39]
I sent the translation files but it did not work.

### System Status

Debug mode	Off
Multisite?	Yes
Site Language	pt_BR
Server	Apache/2
PHP Memory Limit	512 MB
PHP version	5.6.30
MySQL version	 5.1.65

> NanoSupport: v0.3.4

> WordPress: v4.7.4

> Active Theme: TheFox Child Theme – 1.50

> Active Plugins: 
Contact Form 7 (4.7)	by Takayuki Miyoshi
WPBakery Visual Composer (5.0.1)	by Michael M - WPBakery.com
Loco Translate (2.0.13)	by Tim Whitlock
NanoSupport (0.3.4)	by nanodesigns
Slider Revolution (5.3.1.5)	by ThemePunch
Smartsupp Live Chat (3.1)	by Smartsupp
TheFox Custom Post (3.0.0)	by Tranmautritam's Team
WooCommerce PagSeguro (2.12.4)	by Claudio Sanches
WooCommerce (3.0.4)

![image](https://cloud.githubusercontent.com/assets/16905461/25387499/72d29fe4-29a1-11e7-8356-2d36fbc780a1.png)

![image](https://cloud.githubusercontent.com/assets/16905461/25387510/7f1e39de-29a1-11e7-91d4-91a028f8026f.png)

![image](https://cloud.githubusercontent.com/assets/16905461/25387549/9b01fa82-29a1-11e7-8bf9-bc9ef12e6c87.png)

**Comment by mayeenulislam** [comment]
As of the code:
https://github.com/nanodesigns/nanosupport/blob/v0.3.4/nanosupport.php#L59-L67

The language files should go under any of the following places:
- `wp-content/languages/nanosupport/`
- `plugins/nanosupport/i18n/languages/`

BTW, with WP automatic translation update it places nanosupport files under the following path:
- `wp-content/languages/plugins/`

Please note, as of today, the WP glotpress `pt_BR` is **not** 100% translated.
![pt_br-20170425](https://cloud.githubusercontent.com/assets/4551598/25399011/ce648976-2a0f-11e7-88b3-57d3c33ef326.png)
If you translated in your end, that's okay.

I did some tests in my local environment with `pt_BR` translation from the polyglot:
## Test 1: Path: `wp-content/languages/nanosupport/`
:white_check_mark: passed
## Test 2: Path: `plugins/nanosupport/i18n/languages/`
:white_check_mark: passed
## Test 3: Path: `wp-content/languages/plugins/`
:white_check_mark: passed

In all the cases I got the following result:
![support-desk-pt_br](https://cloud.githubusercontent.com/assets/4551598/25401211/edc7a788-2a16-11e7-8451-3e67bdce2990.png)

![nanosupport-pt_br](https://cloud.githubusercontent.com/assets/4551598/25401228/fc988110-2a16-11e7-8ce7-ba8495165c28.png)

What about placing under any of these places?
