### ISSUE TITLE
Cannot select client as author

### ISSUE THREAD

**Issue by mayeenulislam** [nanodesigns/nanosupport#40]
[@mathiasscherer reported](https://wordpress.org/support/topic/selecting-client-as-author/) a default WordPress feature that was intentionally kept to let the Admin add ticket on behalf of their clients (`support_seeker`) isn't working as expected.

We're keeping this as a feature request, and inshALLAH we can do this.

**Comment by elizxer** [comment]
on behlalf of user, how?

**Comment by mayeenulislam** [comment]
Please find the [:notebook_with_decorative_cover: User Guide article on **How to add ticket on behalf of someone else?**](https://github.com/nanodesigns/nanosupport/wiki/How-to-add-ticket-on-behalf-of-someone-else%3F).

**Comment by elizxer** [comment]
thank you very much, you just saved me time and money, hey don't forget to show tickets only specific department and not the whole "MY TICKET"

**Comment by wptech68** [comment]
hi, the "Add the ticket on behalf of anybody" feature in my nanosupport only shows me the users with admin privilegies, but not the full list of the wp users.
Im trying to add a ticket on behalf of a specific end user (subscriber) who can add a ticket by himself, but it doesnt show in the users list, only those with support agents and adminis are showed in the list.
Is this the correct behaviour? Thanks
