### ISSUE TITLE
All tickets assigned to admin when edit

### ISSUE THREAD

**Issue by wptech68** [nanodesigns/nanosupport#44]
recenttly updated to v 0.40 and every time I update, assign the ticket to a agent, or anything from the admin panel it assigns the ticket to me (admin) as the author.

looks the author field at the very bottom of the edit page that only shows the admin in the list changes the author and cannot be changed anymore

**Comment by wptech68** [comment]
for some reason, after updated to 0.40 the real author is not showing the in author list, just the admin shows, so when saving after editing it assigns the admin as the author of the ticket, 
reverted to 0.34 fixed it

**Comment by mayeenulislam** [comment]
Sorry for that. But, I tried editing a Support Seeker's ticket in the admin panel - I cannot recreate the issue:

Please see the "Agent" on the right, and "Author" left below:

## Before update
![before_edit](https://user-images.githubusercontent.com/4551598/28361679-63673cb2-6c9b-11e7-896f-d29d59d2b220.png)

## After update
![after_edit](https://user-images.githubusercontent.com/4551598/28361699-6cbf92aa-6c9b-11e7-9897-87e1255d3918.png)

## Note
BTW, we've noticed a deprecated warning, and already fixed it in our local branch. We will soon publish a fixed version inshALLAH. If that deprecated function is causing the issue - it will fix then inshALLAH.

By the way, **could you please share the System Information** you are using, if possible we'll try to recreate the issue using a similar setup inshALLAH.

**Comment by wptech68** [comment]
![nano1](https://user-images.githubusercontent.com/24855177/28380762-e4529a2c-6c8e-11e7-92e5-742081ce1491.png)
![nano2](https://user-images.githubusercontent.com/24855177/28380761-e4471f9e-6c8e-11e7-8015-e2d52c29d140.png)

using last WP 4.8 
BTW, I did not uninstalled v0.34, just replaced every file with the ones in v0.40

**Comment by mayeenulislam** [comment]
> _{screenshots}_

Your scenario and bug report is quite understandable. BTW thanks for the screenshots too.

> using last WP 4.8

I'm afraid, only WordPress version is not enough. Please get to **Admin Panel &raquo; NanoSupport &raquo; System Status**<br>
In `v0.4.0` you can copy all the system status using a single click. After copying you can paste the information here. That will help us debugging the issue.

> BTW, I did not uninstalled v0.34, just replaced every file with the ones in v0.40

Hmm, that's fine until we change the Plugin directory name. 😃

**Comment by mayeenulislam** [comment]
Could you please use the following fixed version of NanoSupport? It has the fix for the deprecated declaration. Please inform what's the result.

[:arrow_down: nanosupport-0.4.0-fix.zip](https://github.com/nanodesigns/nanosupport/files/1163398/nanosupport-0.4.0-fix.zip)

**Comment by wptech68** [comment]
same error with  the 0.4.0 FIX version, does not show the author in the list, just the admin
reverting to 034 since it works fine

status
![nano3](https://user-images.githubusercontent.com/24855177/28438233-d0b8a64c-6d73-11e7-9998-3b647a9aa3a1.png)

**Comment by mayeenulislam** [comment]
Could you please try this fixed version?<br>
[:arrow_down: nanosupport-0.4.0-fix-2.zip](https://github.com/nanodesigns/nanosupport/files/1165978/nanosupport-0.4.0-fix-2.zip)

We've removed the previous code and replaced with a core filter. This should fix the issue inshALLAH.

**Comment by wptech68** [comment]
That worked !!!
thanks

**Comment by mayeenulislam** [comment]
Aah! Relief. :smile:
We're going for a release with this fixed version, soon inshALLAH.
