### ISSUE TITLE
Hope to add import feature

### ISSUE THREAD

**Issue by fang-yu** [nanodesigns/nanosupport#46]
Love Nanosupport!

We have 1500 knowledge base docs, but seems like nano does not support import function, hope can add this feature in the future.

**Comment by mayeenulislam** [comment]
> We have 1500 knowledge base docs, but seems like nano does not support import function, hope can add this feature in the future.

@fang-yu Sorry, can't get you. NanoSupport supports the WordPress Export and Import feature as expected. You can export NS Knowledgebase docs and can import into another NanoSupport desk:

## Export
![nskb-export](https://user-images.githubusercontent.com/4551598/32182610-4dac16f0-bdc1-11e7-9952-783b8426d3ec.png)

## Import
![nskb-import](https://user-images.githubusercontent.com/4551598/32182622-562f5742-bdc1-11e7-9aef-1cec8ed94295.png)

**Comment by fang-yu** [comment]
@mayeenulislam thanks! I got that!
