### ISSUE TITLE
Clickeable links on tickets

### ISSUE THREAD

**Issue by wptech68** [nanodesigns/nanosupport#54]
Improvement request
hi, when adding a URL address to the ticket it should link to the target link in a new window, now it just shows as plain text. thanks

**Comment by mayeenulislam** [comment]
Thanks for the feature request.

But I guess the rich text editor is available on the front end ticket submission form and you have full ability to control how the link would be.

**Step 1:**<br>
![link-1](https://user-images.githubusercontent.com/4551598/38355358-7a0164ec-38de-11e8-8b26-69452b2ff677.png)

**Step 2:**<br>
![link-2](https://user-images.githubusercontent.com/4551598/38355366-7f53c098-38de-11e8-8538-9d1230e28077.png)

And the tickets are private, hence no SEO issue would be there. I think this is what you want, and it's already there.

**Comment by wptech68** [comment]
yes, I mean the response box where there is no rich text editor
