### ISSUE TITLE
Please take over Feature request

### ISSUE THREAD

**Issue by alexlii1971** [nanodesigns/nanosupport#56]
Hello，

This is not issue report, but a request to take over another plugin if possible.

https://wordpress.org/plugins/feature-request/

I am just thinking it would be great if you can take over this plugin since it was out of maintenance by the author, since Ticket Support and feature request are both closely related to feedback from users.

For now, that plugin works well, but if enable debug, there will be lots of error at frontend with wordpress 4.9.6.

and let me know what you think.

Thanks.

Alex

**Comment by mayeenulislam** [comment]
:smile: Thanks for informing us and thinking us eligible for it. We're grateful for it.

It might be a good Feature Request. BTW acquiring an existing product or releasing a new product both require huge new workload, that, we're afraid, we currently are not capable of.

Thank you for your suggestion again.
We'll pass this request to the WordPress Development community for a better call to acquire this.
Thanks again.

**Comment by alexlii1971** [comment]
Thanks, I understand.

Usually, we may receive lots of support tickets, but these actually not support tickets but feature requests.

So, I really these two functions are closely related.

If possible, it is worth to do.
