### ISSUE TITLE
changing style to rtl

### ISSUE THREAD

**Issue by Qamdad** [nanodesigns/nanosupport#58]
Hello,

your plugin looks great in mobile but in desktop for rtl/arabic language need some change if you could help me. It looks like this in desktop using Avada theme https://i.imgur.com/0dJGT6L.png it should exchange between red and green box in the screenshot I provide. any Idea please? 

Thanks in advance

**Comment by mayeenulislam** [comment]
You can consult the [FAQ](https://github.com/nanodesigns/nanosupport/wiki/Frequently-Asked-Questions) saying: "How the plugin can be well integrated with my theme?"

If you need any further assistance, you can write here.
