### ISSUE TITLE
Validating the Receipt on Ticket Submission

### ISSUE THREAD

**Issue by mauwiks** [nanodesigns/nanosupport#63]
Hi, Nano Designs!

Support Ticket Page doesn't verify or validate the purchase receipt number as per product.

Here are the screenshots: 
http://prntscr.com/kuxl9e (Successful submission)
http://prntscr.com/kuxj6t (Setting of Product Receipt)

I expect that it should verify the receipt as per integrated on the e-commerce solution plugin (if available) then it will continue to let the support seeker submit the ticket issue.

Basically, I would like the support system to validate the purchase receipt as per product prior to continuing to the action of submitting the ticket on the submit ticket page. The problem is that when I tried to input a random number or character on the purchase receipt, it still proceed to submit the ticket. How can we restrict users to submit an issue that is not validated as per product receipt?

### System Status

WordPress version: 4.9.8;
NanoSupport version: 0.5.0;
E-Commerce?: Enabled;
Active Theme: Themedd - Child Theme - 1.0.0;  — Parent Theme: Themedd - 1.0.6;
Debug mode: Off;
Multisite?: No;
Site Language: en_US;
Server: Apache;
PHP Memory Limit: 512 MB;
PHP version: 7.2.9;
MySQL version: 5.6.41.

...

Active Plugins (11):
CF7 Mautic Extention (0.0.5) - by hideokamoto; Contact Form 7 (5.0.4) - by Takayuki Miyoshi; Cookie Notice (1.2.44) - by dFactory; Easy Digital Downloads (2.9.7) - by Easy Digital Downloads; Easy Digital Downloads - Downloads As Services (1.0.6) - by Easy Digital Downloads; Easy Digital Downloads - External Products (1.1.0) - by Daniel J Griffiths; Featured Image From URL (1.9.5) - by Marcel Jacques Machado; Gutenberg (3.8.0) - by Gutenberg Team; NanoSupport (0.5.0) - by nanodesigns; Regenerate Thumbnails (3.0.2) - by Alex Mills (Viper007Bond); WordPress Importer (0.6.4) - by wordpressdotorg.

**Comment by mayeenulislam** [comment]
Hello @mauwiks. Thanks for notifying the issue.

Validating the receipt was not actually planned. If the receipt if invalid, the link to the receipt won't appear in Admin Panel. So, you now know that, the ticket is about an invalid purchase.

But validation is a good feature that we missed for sure. Let's take it to the roadmap of `v5.0.1`, inshALLAH.

**Comment by mauwiks** [comment]
Thanks! Will count on that. 

Another thing. If it is not validated, is there a functionality to not prioritize the ticket?

**Comment by mauwiks** [comment]
I would also like to edit the Product text into services. Is it possible?

**Comment by mayeenulislam** [comment]
Can we discuss different issue on different thread? It will help our future reference.

**Comment by mayeenulislam** [comment]
@mauwiks What does the word "Validate" mean here? Checking whether the Receipt id exists in the database, or not - right?

**Comment by mauwiks** [comment]
Yes. And if not validated, we can have a setting to restrict a guest (support seeker) on submitting a ticket. This is mostly the case that a premium support (paid service) would want as a functionality, but if there is a possible solution to categorize a submitted ticket into a "low priority" (ticket status) when there is no valid receipt were submitted, I'll appreciate if you can give me some link or idea for this solution.

**Comment by mayeenulislam** [comment]
Thanks a lot. Loved the idea or prioritizing, based on the validation. Will reach you with a solid plan, inshALLAH, soon.

**Comment by mauwiks** [comment]
Thanks. Looking forward to it.

**Comment by mayeenulislam** [comment]
Will be available with `v0.5.1` inshALLAH soon

**Comment by mauwiks** [comment]
Exciting...
