### ISSUE TITLE
Knowlegebase Feature Ideas

### ISSUE THREAD

**Issue by mauwiks** [nanodesigns/nanosupport#66]
I hope the following features will be considered soon:

1. Auto Suggests when Submitting a Ticket
2. Letting the Support Agent forward a Knowledge Base existing solution

**Comment by mayeenulislam** [comment]
@mauwiks Thank you for suggesting new features, but can we stick to a single point in a single issue? That would help us maintain issues separately and to-the-point.

BTW Issue 1 is a duplicate to #18 .

Cannot understand _Support Agent forward a Knowledge Base existing solution_. Could you please elaborate?

**Comment by mauwiks** [comment]
Alright!

> Cannot understand Support Agent forward a Knowledge Base existing solution. Could you please elaborate?

What I mean is when a Support Agent tries to answer an issue, it would be nice if the available Knowledge Base articles. the Agent could Auto-Suggest some solutions.

**Comment by mayeenulislam** [comment]
Don't you think it requires Artificial Intelligence?

How is your logic to fetch recommended KB articles for a ticket? How would you search for them?

**Comment by mauwiks** [comment]
Hi @mayeenulislam,

Please see attached screenshot and note: http://prntscr.com/kxgn5o

Best regards

**Comment by mayeenulislam** [comment]
We are glad to announce the first Premium Add-on for NanoSupport:

> [**Addon: Knowledgebase Search** - NanoSupport](https://creativemarket.com/nanodesigns/3461090-NanoSupport-Knowledgebase-Search?ref=nsgithub)

Requires NanoSupport `v0.6.0`

It will suggest from the Knowledgebase Docs while submitting a new ticket, and it will enable a separate search feature in Knowledgebase. 😃
