### ISSUE TITLE
Purchase text Wrong Spelled

### ISSUE THREAD

**Issue by mauwiks** [nanodesigns/nanosupport#68]
How can I edit this text? http://prntscr.com/kyzw1h

Can I do a tweak somewhere to edit this? Locate at Submit Ticket Page. I tried the code here [#9](https://github.com/nanodesigns/nanosupport/issues/9) but it broke my site. lol.

Thanks.

Best regards,

**Comment by mauwiks** [comment]
Is there a way to edit this? I could not find it somewhere in the plugin's directory files

**Comment by mayeenulislam** [comment]
You can correct the spelling here: `includes/shortcodes/ns-submit-ticket.php` at line number `302` [(source)](https://github.com/nanodesigns/nanosupport/blob/v0.5.0/includes/shortcodes/ns-submit-ticket.php#L302)

**Comment by mauwiks** [comment]
Thank you @mayeenulislam
