### ISSUE TITLE
Transfer NanoSupport to another domain

### ISSUE THREAD

**Issue by mauwiks** [nanodesigns/nanosupport#72]
What is the simplest way to backup and restore the plugin with the knowledgebase articles to a different location or domain?

I got my NanoSupport under domain.com/shop installed and I would like to have it in the root.

This just means, I want to move the plugin to another WordPress in my root domain instead under the current subdirectory

**Comment by mayeenulislam** [comment]
Thanks for asking. We've added a detailed Documentation on this issue after your query. Hope it helps.

> **Documentation: Export-Import NanoSupport Data**
> https://github.com/nanodesigns/nanosupport/wiki/Export-Import-NanoSupport-Data
