### ISSUE TITLE
Standalone knowledgebase plugin

### ISSUE THREAD

**Issue by mauwiks** [nanodesigns/nanosupport#73]
Is there a way to use the Knowledgebase alone with the plugin? Or do you have plans to support a Knowledge Base plugin with NanoSupport KB alone?

**Comment by mayeenulislam** [comment]
Knowledgebase can be developed separately, but we don't currently have that plan actually.

And we don't want to separate Knowledgebase from the NanoSupport as they are interrelated: we're redirecting public users from the Private zone to the Public Knowledgebase and there are other dependencies.

We're sorry for your inconvenience.

PS. There is a way to enable/disable Knowledgebase apart from the Support Desk
