### ISSUE TITLE
ticket creation date lost when agent assigns the ticket

### ISSUE THREAD

**Issue by wptech68** [nanodesigns/nanosupport#74]
looks that the first creating date is lost when the support agent assigns the ticket, or basically when it moves from pending to open status

as an example:
user creates a ticket on march 1st, so it has a pending status till an agent reaches it
support agent sees the ticket 1 week later on march 8 and assign this ticket to someone
now, the ticket shows both creation and update date as march 8, when it was originally created on march 1st, however this first date is missed forever.

i think the ticket shoud keep the march 1 as the creation date, and march 8 as the updated one.
if missed as now, nobody can see how many days the agent waited to assign the ticket, actually the march 1st date is removed from everywhere including the admin console, so not even a full admin can view when it was originally posted by the user

hope it helps

**Comment by mayeenulislam** [comment]
You have a very good point asking for the feature. But, this is a feature of WordPress core, by default.
Primary observation shows, there's no quick filter hook available to reverse the feature.
Tried some inner hooks to get the desired value, but it simply appears that, currently it's a 'won't fix' request.
But we will obviously take a look at how to achieve this with least performance clutter.

**Comment by wptech68** [comment]
not a big problem , just a suggestion.
thanks anyway to take in consideration
bye
