### ISSUE TITLE
Template problems with ver 0.6.0

### ISSUE THREAD

**Issue by wptech68** [nanodesigns/nanosupport#76]
unfortunately, v060 didnt work at all in my theme, the single ticket page only loads the theme header and footer with a white line in the middle where the content should be shown, reverted to v 051 while I investigate a bit more.

**Comment by mayeenulislam** [comment]
With the release of `v0.6.0` the `templates/content-single-ticket.php` had major changes.
You need to copy the new template into your theme and change where necessary.

> We agree the templates are not easy tasks to edit, but please be assured we're on the way to fixing templates for easy modifications.
