### ISSUE TITLE
page sidebar default

### ISSUE THREAD

**Issue by deltaforce** [nanodesigns/nanosupport#80]
When creating a KB article, is there any way to make it default to NO SIDEBAR ?

**Comment by mayeenulislam** [comment]
@deltaforce Yes, indeed. But that's the task in the Theme territory.

In your theme, make a copy of the `single.php` and name it `single-nanodoc.php`:

```
mytheme/
   |--→ single.php
   |--→ single-nanodoc.php
```

Open `single-nanodoc.php` in a code editor, and remove or comment-out the line:
```php
<?php // get_sidebar(); ?>
```

If you are working on a third-party theme, [make a child theme](https://developer.wordpress.org/themes/advanced-topics/child-themes/) of it to not lose the changes when upgrading the theme later, and do the above-mentioned changes in the child theme.

Good luck.

----
<sup>Would love to have [a ⭐️⭐️⭐️⭐️⭐️ (5-star) Review](https://wordpress.org/support/plugin/nanosupport/reviews/#new-post) from you if you love using NanoSupport.</sup>
