### ISSUE TITLE
Disable User Login Requirement?

### ISSUE THREAD

**Issue by hostbend** [nanodesigns/nanosupport#89]
Can we make it so that you don't have to have a WordPress account to submit a ticket? We don't use WordPress for user management so our customers aren't going to like the fact that they'll need two separate logins.

**Comment by mayeenulislam** [comment]
One of the banner-point of NanoSupport is "WordPress-way", where we used WordPress Authentication and Role & Capabilities features, like `current_user_can()`, `is_user()` etc.

Without WordPress authentication in a WordPress site how are you managing the User Auth part? Without knowing details we can't say a brief 'Yes' or 'No'.

**Comment by hostbend** [comment]
Our business uses WordPress more like a Content Management System. We utilize a different tool for billing and automating our services, but we were intrigued by your WordPress plugin. The only thing holding us off is that only WordPress users can submit tickets.

Simply adding a name and email field (without creating a WordPress account) would be fine. It's okay if that's not possible, but we really liked the plugin.

**Comment by mayeenulislam** [comment]
We are afraid, the plugin is a WordPress plugin and was intended to use within the scope of WordPress alone.

We are extremely sorry that, we can't support you on this issue.

If you like the plugin, we request you to rate us a 5-star (⭐⭐⭐⭐⭐) to let us grow...
https://wordpress.org/support/plugin/nanosupport/reviews/#new-post
