### ISSUE TITLE
Can't submit

### ISSUE THREAD

**Issue by gjrowe** [nanodesigns/nanosupport#92]
**Describe the bug**
When submitting a ticket it says the description can't be blank

**To Reproduce**
Submit a ticket with a description and hit submit. The description will disappear and the error will show.

**Expected behavior**

**Screenshots**

**System Status (you can copy paste the system status report from the plugin):**

WordPress version | 5.4.1
-- | --
0.6.0
Disabled
Converio Child Theme – 1.0.0
Converio – 1.0.35
Off
No
en_US
Apache
256 MB
7.1.24 — We recommend a minimum PHP version of 7.3. See: WordPress minimum requirements
5.6.41

**Additional context**

**Comment by mayeenulislam** [comment]
I'm afraid, we can't get your issue. You are trying to say, you are putting description, but it's still saying "Description can't be blank". We cannot reproduce the issue. You can check too:
http://dev.nanodesignsbd.com/submit-ticket/

### Troubleshooting
Before going any further, it's better to troubleshoot what's actually is happening there. Here's a quick guide for you:
https://github.com/nanodesigns/nanosupport/wiki/Troubleshooting-NanoSupport

We request you to follow the instructions properly.

**Comment by gjrowe** [comment]
Hmmm... I tried disabling plugins and trying with no success. I just tried disabling Advanced Custom Fields again. It worked after disabling it. When I reactivated Advanced Custom Fields it still worked. Strange !   Not sure why it did not work the first time I disabled either.

**Comment by gjrowe** [comment]
There seems to be a conflict with the "Advanced Custom Fields" plugin

**Comment by gjrowe** [comment]
Found the issue... Not a conflict... poorly written code on my end... Called "acf_form_head();" for Advanced Custom Fields in the theme functions as opposed to just the pages that need it.
