### ISSUE TITLE
Linking notifications plugin with nanosupport

### ISSUE THREAD

**Issue by DavidAni123** [nanodesigns/nanosupport#94]
I have a notifications plugin that sends notifications to users and specific roles on a post publish, update etc. I would like it to work with a ticket creation. So when a ticket is created it sends the notifications to the authors and agent, admin etc. The plugin currently works on page posts in wordpress but not on ticket posts in nanosupport. was wondering if they could be configured to work together or if on the creation of a ticket im able to create a new post automatically and then send the notifications from the new post. Plugin is Notification by BracketSpace. System status is below.

WordPress version: 5.4.1;
NanoSupport version: 0.6.0;
E-Commerce?: Disabled;
Active Theme: Twenty Twenty - 1.2; ;
Debug mode: Off;
Multisite?: No;
Site Language: en_US;
Server: nginx/1.10.3;
PHP Memory Limit: 256 MB;
PHP version: 7.4.5;
MySQL version: 5.5.5.

...

Active Plugins (3):
NanoSupport (0.6.0) - by nanodesigns; Notification (7.0.4) - by BracketSpace; Guaven SQL Charts (2.1.2) - by Guaven Labs.

**Comment by mayeenulislam** [comment]
We've explored the Notification plugin by BracketSpace. First of all it's a nice plugin. :)

But it's unclear with what Settings the plugin works with Custom Post Types in your case, like 'Tickets' (`nanosupport`). I tried disabling all the email functions and interruptions from NanoSupport, and added the post type "Tickets" to the trigger, but it's still not triggering any email.

I then tried with "Knowledgebase" where no email was configured by the NanoSupport, but it's still not triggering any email.

So I suspected something might be wrong with the NanoSupport. But with this suspicion I then tried enabling trigger for WooCommerce's post type 'Product'. But it still not triggering any email on Product update, while it's triggering email on Post update, where post is a native post type.

My suspicion is, *the Notification plugin is not supporting any Custom Post Type*, though they declared they supports Custom Post Type.

To prove my theory, I then:
- Disabled all my plugins but the Notification
- The default TwentyTwenty theme was enabled
- And in the theme's `functions.php`, I added code to create a makeshift custom post type 'book' with [code from the Codex](https://codex.wordpress.org/Function_Reference/register_post_type).
- I then add trigger for 'Books' from the Notification plugin settings
- But it still cannot trigger any email

Tested with WordPress v5.4.1.

## How to make NanoSupport work for the Notification?
If the Notification plugin works with Custom Post Types (CPTs), then doing the following should work for NanoSupport too (not tested):

- Add the following line to the theme's `functions.php`:
`remove_filter('comment_notification_recipients', 'ns_disable_wp_comment_notification', PHP_INT_MAX);`
- Uncheck all the checkboxes on NanoSupport Email Settings under the NanoSupport &raquo; Settings

Hoping for the best.
