### ISSUE TITLE
Knowledgebase Search Plugin Not working

### ISSUE THREAD

**Issue by deonvisser** [nanodesigns/nanosupport#97]
The plugin fails to install it says that No such plugin exists on installation.

This is the system details.....

NanoSupport Environment
--
5.4.1
0.6.0
Disabled
BuddyBoss Child – 1.0.0
BuddyBoss Theme – 1.5.0
Off
No
en_US
Apache
256 MB
7.3.18-1+0~20200515.59+debian9~1.gbp12fa4f
5.5.5 — We recommend a minimum MySQL version of 5.6. See: WordPress minimum requirements

I am running mariaDB.

**Comment by mayeenulislam** [comment]
Can you please write us at: `support@nanodesignsbd.com`?

Would love to have your email with the following things:

1. A screenshot of the error, and
2. what are the steps you followed on installing the plugin

**Comment by mayeenulislam** [comment]
As no email received. Hopefully you figured out the issue by yourself.
FYKI, there's a User Manual on the first zip file, which will guide you on everything, inshaALLAH.
Thank you for using our product.
Closing here.
