### ISSUE TITLE
Page notifications

### ISSUE THREAD

**Issue by rushhourmediayyc** [nanodesigns/nanosupport#99]
The notification bar that appears after a user action on the ticket page is pushed right to the top of the page & gets lost under my transparent heading. Is there a way to move them down?

https://www.loom.com/share/12e10160e3264c5b844c26f4271125be

**Comment by mayeenulislam** [comment]
Hello @rushhourmediayyc 
Thanks for reaching us.

I'm afraid, there is no such notification bar thing is embedded with NanoSupport. Hence we can't see what you are talking about? Can you please highlight what you are talking about in this URL:
http://dev.nanodesignsbd.com/submit-ticket/
